# Generated by Django 4.2.3 on 2023-08-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('picture', models.ImageField(upload_to='event_pictures/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('distance', models.PositiveIntegerField(default=10, help_text='Maximum distance (in kilometers) you are willing to travel for events.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.eventcategory')),
            ],
        ),
    ]
