# Generated by Django 4.2.3 on 2023-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(max_length=150),
        ),
    ]
