# Generated by Django 4.2.3 on 2023-08-02 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_category', models.CharField(choices=[('Conference', 'Conference'), ('Concert', 'Concert'), ('Workshop', 'Workshop'), ('Party', 'Party'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], max_length=20)),
                ('picture', models.ImageField(upload_to='event_pictures/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
