# Generated by Django 4.2.3 on 2023-08-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_distance', models.PositiveIntegerField(default=10, help_text='Maximum distance (in kilometers) you are willing to travel for events.')),
                ('prefered_categories', models.ManyToManyField(blank=True, help_text='Select your preferred event categories.', related_name='interested_users', to='Auth.eventcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.eventcategory'),
        ),
    ]
