# Generated by Django 4.2.3 on 2023-08-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('Auth', '0003_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefered_categories',
            field=models.ManyToManyField(blank=True, help_text='Select your preferred event categories.', related_name='interested_users', to='base.eventcategory'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
